pipeline {
    agent {
        label "AGENT-1"
    }

    tools {
        nodejs 'nodejs-20'
    }

    options {
        timeout(time:30, unit:'MINUTES') 
    }

    environment{
        ACC_ID = "196061557685"
        AWS_REGION = 'us-east-1'
        PROJECT = "roboshop"
        COMPONENT = "catalogue"
        appVersion = ""
    }

    stages {
        stage("cleanup") {
            steps {
                deleteDir()
            }
        }

    stage('Checkout') {
        steps {
            git branch: 'main', url: 'https://github.com/Dinakar-Dasari/jenkins_practise.git'
        }
    }

    stage('Verify Workspace') {
        steps {
            sh 'pwd'
            sh 'ls -R'
        }
    }        

        stage("version") {
            steps {
                dir('day2') {
                    script {
                        def packageJson = readJSON file: 'package.json'
                        appVersion = packageJson.version
                        echo "Package version: ${appVersion}"
                    }     
                }         
            }
        }

        stage("install dependencies"){
            steps {
                dir('day2') {
                    sh 'npm install' 
                }
            }    
        }

        stage("dependency scan") {
            steps {
                echo "Will scan using OWASP Dependency-Check"
            }
        }

        stage('unit tests') {
            steps {
                echo "testing unit"
            }
        }

        stage("SAST scan"){
            steps{
                echo "will scan using sonarQube"
            }
        }

        stage("image build"){
            steps{
                dir('day2'){
                    withAWS(credentials: 'aws-creds', region: "${REGION}") {
                    sh """
                        aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com
                        docker build -t ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com/${PROJECT}/${COMPONENT}:${appVersion} .
                        docker push ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com/${PROJECT}/${COMPONENT}:${appVersion}
                    """
                    }
                }
            }    
        }

        stage("image scan") {
            steps {
                echo "will scan using trivy"
            }
        }
    }

    post { 
        success { 
            echo 'Hello Success'
        }
        failure { 
            echo 'Hello Failure'
        }
    }

}