pipeline{
    agent {
        label "AGENT-1"
    }

    options{
        timeout()
        disableConcurrentBuild()
    }

    environment{
        DAY = "1"
        PROJECT = "roboshop"
    }

    stages{
        stage("pre-stage"){
            steps{
               deleteDir()     
            }
        }
        stage("stage-1"){
            steps{
                echo "stage-1"
                echo "$DAY of $PROJECT "  
            }          
        }

        stage("stage-2"){
            steps {
                echo "second stage"
            }
        }
    }

    post{
        always{
            steps{
                echo "anyways, Hello"

            }
        }

        success{
            steps{
                echo "Hello, success"
            }
            
        }

        failure{
            steps{
                echo "Hello, fail"
            }
            
        }
    }
}