pipeline{
    agent {
        label "AGENT-1"
    }

    options{
        timeout(time: 1, unit: 'HOURS')
        disableConcurrentBuilds()
    }

    environment{
        DAY = "1"
        PROJECT = "roboshop"
    }

    stages{
        stage("pre-stage"){
            steps{
               deleteDir()     
            }
        }
        stage("stage-1"){
            steps{
                echo "stage-1"
                echo "$DAY of $PROJECT "  
            }          
        }

        stage("stage-2"){
            steps {
                echo "second stage"
            }
        }
    }

    post{
        always{
                echo "anyways, Hello"
        }

        success{
                echo "Hello, success" 
        }

        failure{
                echo "Hello, fail"
        }
    }
}